### ISSUE TITLE
Docker install stuck in a loop

### ISSUE THREAD

**Issue by Illuminatian** [chaoss/grimoirelab-tutorial#10]
Following the tutorial instructions on installing the GrimoireLab docker container is resulting in what seems to be an endless loop. The installation seems to be proceeding fine, Elasticsearch, MaridaDB, and Kibiter all seem to initialize fine, however once it gets to the Mordred portion I get my first error of "Error: db assigned", which is then immediately followed by a string of 401 errors in the form of:

``"grimoire_elk.arthur - ERROR - Error feeding ocean from github (https://github.com/grimoirelab/arthur): 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/arthur.py", line 196, in feed_backend
    ocean_backend.feed()``

The python trace then follows, and then another 401 error occurs:
``2018-02-05 20:10:18,057 - grimoire_elk.arthur - ERROR - Error feeding ocean from github (https://github.com/grimoirelab/grimoireelk): 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/arthur.py", line 196, in feed_backend
    ocean_backend.feed()``

So on and so forth for the following directories: 
https://github.com/grimoirelab/mordred
https://github.com/grimoirelab/panels
https://github.com/grimoirelab/perceval
https://github.com/grimoirelab/perceval-mozilla
https://github.com/grimoirelab/perceval-opnfv
https://github.com/grimoirelab/perceval-puppet
https://github.com/grimoirelab/sortinghat
https://github.com/chaoss/grimoirelab
https://github.com/chaoss/grimoirelab-kidash
https://github.com/chaoss/grimoirelab-manuscripts
https://github.com/chaoss/grimoirelab-tutorial

After it errors on each of those, I get the following messages:
``23/23 unique identities loaded
Elasticsearch aliases: creating...
Elasticsearch aliases: created!
Elasticsearch aliases: creating...
Elasticsearch aliases: created!
Loading blacklist...
0/0 blacklist entries loaded
Loading unique identities...
23/23 unique identities loaded``

...and then it transitions back into the 401 errors. I've let the install run about 10 minutes with no change, which makes me feel that it's caught in a loop.

Any ideas on what the problem could be?

**Comment by jgbarah** [comment]
Thanks a lot for the report.

The first error (Error: db assigned) is not really an error. I'm working to identify it, but I guess it is just that in some cases, the system tries to create a database which already exists. But that should not be any problem.

The other error is very likely due to exhausting the GitHub API. Did you include your (valid) GitHub API token in the `mordred-override.cfg` file? Or just let me know how exactly you're launching the container, and what's in the file that you specify.

Yes, the system is in a loop, but that's right. In fact, mordred launches several threads. One of them is periodically checking identities found, and trying to unify them according to some heuristics an an indentities file that the container has. It is configured to do that frequently (like every 10 sec.) so that you have unified identities in the dashboard as soon as possible.

**Comment by jgbarah** [comment]
Hmmm. I've realized the tutorial was referring to a deprecated set of files for configuring Mordred. The right ones are those in the slides of my presentation at FOSDEM. I'm sorry for this error. I´ ve updated the section on installing with Mordred containers, and should be fine now.

The error was that it mentioned `/mordred-local.cfg` instead of `/mordred-override.cfg`, which is the right file. Please, if you we using the command line for running the container as in the tutorial, refresh your page about running Mordred from a container, and run it as it is now in that page:

```
$ docker run -p 127.0.0.1:5601:5601 \
    -v $(pwd)/credentials.cfg:/mordred-override.cfg \
    -t grimoirelab/full
```

**Comment by Illuminatian** [comment]
I've been following the instructions listed at https://grimoirelab.gitbooks.io/tutorial/before-you-start/deploying-from-dockerhub.html , and they don't seem to be updated yet. I ran the new command you listed above, however now i'm running into a new error
``C:\Program Files\Docker Toolbox\docker.exe: Error response from daemon: OCI runtime create failed: container_linux.go:296: starting container process caused "process_linux.go:398: container init caused \"rootfs_linux.go:58: mounting \\\"/c/Users/jacob/credentials.cfg\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/570e322374cbd88a3df0bbef29d79a969b1fe9a83f7eb691c1eb93515a36599b\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/570e322374cbd88a3df0bbef29d79a969b1fe9a83f7eb691c1eb93515a36599b/mordred-override.cfg\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.``

Any suggestions as to the cause of this one?

**Comment by jgbarah** [comment]
Again, you're right. I did fix [Running Mordred from a container](https://grimoirelab.gitbooks.io/tutorial/mordred/mordred-in-a-container.html) but not the reference that you mention, which is indeed the most visible, since it is at the beginning of the book. I just fixed it, should be correct by now.

WRT your error, it seems you're not having the `credentials.cfg` file in the current directory (the directory from which you're launching the container). Could you please check that? It should be there, with read permissions, and with this content:

```
[github]
api-token = XXX
```

(of course, with your real GitHub API token instead of XXX).

Besides, I see you're running the container in Windows. If you succeed, please let me know which version of Windows you're using: most tests have been run with Linux, and we don't have many Windows machines around.

**Comment by Illuminatian** [comment]
I'm currently running Windows 10 Home edition, Version 1709, Build 16299.125

I made sure I had the credentials.cfg in the right place, it got nested under another folder, so I moved it back to the pwd, however that still wasn't working. I ended up deleting the VM created for the container and doing a full redownload/run of the docker image. Currently it's at the blacklist/unique identities portion of the install and the error messages aren't popping up
```Error: db assigned
Loading blacklist...
0/0 blacklist entries loaded
Loading unique identities...
23/23 unique identities loaded
Loading blacklist...
0/0 blacklist entries loaded
Loading unique identities...
23/23 unique identities loaded
Loading blacklist...
0/0 blacklist entries loaded
Loading unique identities...
23/23 unique identities loaded
```

is where i'm at so far. Is that looking correct?

**Comment by Illuminatian** [comment]
Ok, I think it may be stuck in a loop again, about 3 minutes after I posted my last comment, i received this error
```
2018-02-07 01:54:26,821 - grimoire_elk.arthur - ERROR - Error feeding ocean from git (https://github.com/chaoss/grimoirelab): git command - Cloning into bare repository '/home/grimoirelab/.perceval/repositories/https://github.com/chaoss/grimoirelab-git'...
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/arthur.py", line 196, in feed_backend
    ocean_backend.feed()
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/ocean/elastic.py", line 204, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/ocean/elastic.py", line 214, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 129, in fetch
    for item in self.fetch_items(**kwargs):
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 132, in fetch_items
    latest_items)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 253, in __fetch_from_repo
    repo = self.__create_git_repository()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 298, in __create_git_repository
    repo = GitRepository.clone(self.uri, self.gitpath)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 796, in clone
    cls._exec(cmd, env=env)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/git.py", line 1257, in _exec
    raise RepositoryError(cause=cause)
perceval.errors.RepositoryError: git command - Cloning into bare repository '/home/grimoirelab/.perceval/repositories/https://github.com/chaoss/grimoirelab-git'...
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
```

Now i've left it running for about 10 min and it just keeps repeating the "Loading blacklist, loading unique identities" lines over and over....

**Comment by jgbarah** [comment]
Hi again! It seems you're finding all the problems :-(

Look, it seems this is a kind of a bug in the SSL library git is using. It seems it can happen for several reasons, one of them is being behind a firewall or proxy. Is that your case? The more information you can provide about how you connect to the Internet the better, to try to reproduce your issue.

More documentation about the problem: [The remote end hung up unexpectedly while git cloning](https://stackoverflow.com/questions/6842687/the-remote-end-hung-up-unexpectedly-while-git-cloning).

It seems that in some cases, setting `git config --global http.postBuffer 1048576000` seems to work. I'm going to produce a testing container for you, with that fix, so that you try to see if it works.

**Comment by Illuminatian** [comment]
Finding problems is a good thing, it means things will be ironed out of people in the future! It may have been a windows firewall issue, I just got this laptop and haven't quite finished tweaking it yet. I'll make sure it's disabled before the next run through. I really appreciate that you're making me my own special container, I'm more than happy to help be your Windows guinea pig!

**Comment by jgbarah** [comment]
> Finding problems is a good thing, it means things will be ironed out of people in the future!

Yes, indeed!

> It may have been a windows firewall issue, I just got this laptop and haven't quite finished tweaking it yet. I'll make sure it's disabled before the next run through. I really appreciate that you're making me my own special container, I'm more than happy to help be your Windows guinea pig!

I take your word ;-) 

Please, test the new container `grimoirelab/full:testing`. Use it exactly the same way that you used `grimoirelab/full`, just changing its name by this new one. The main difference is that I set up the `http.postBuffer` to 1 GB, although I'm not sure that was the problem.

I suggest you try to find out if this one works as intended, and if you succeed, then do the same with the "standard" one `grimoirelab/full` again, just in case.

Thanks for your help!!

**Comment by Illuminatian** [comment]
Well, tried the new container.  No proxy or firewall issues for sure this time. Didn't receive the error, however I've been watching it load blacklist entries, unique identities, and create Elasticsearch Aliases for about a half hour now. It seems to be caught in a quasi-random repeat, with a different number of each action block happening on each go around. How many times on a typical install should i see
```
Loading blacklist...
0/0 blacklist entries loaded
Loading unique identities...
23/23 unique identities loaded
Elasticsearch aliases: creating...
Elasticsearch aliases: created!
```
happening?

**Comment by jgbarah** [comment]
It is in incremental mode (that is, do stuff once and again, checking for fresh data from original data sources). The period for the refresh is short, so that the demo works better (for a real deployment this is a parameter you can configure).

In other words, if there was no error in the output, it is very likely that it worked, and you have your dashboard ready and updating. Did you check at http://127.0.0.1:5601 ?

**Comment by Illuminatian** [comment]
I did check http://127.0.0.1:5601, however all i got was the chrome generic "Site can't be reached" error.

**Comment by jgbarah** [comment]
Weird. If you launched the container with the -p option, usually either you get an error when launching, or the container runs and something is the attached to the 5601 port... How did you exactly launched the container?

**Comment by Illuminatian** [comment]
Sorry it's taken so long to respond, it's been a busy week. I ran docker exactly as prescribed, this time doing another fresh start, and still getting the same error when trying to get to 127.0.0.1:5601.

Is it possible that the config file for mordred needs more information in it? I don't know, I'm drawing a blank

**Comment by Illuminatian** [comment]
Ok, so i think I've narrowed the problem down. When i try to access 127.0.0.1:5601 on my host machine, it's just looking at the localhost, when I need it to be looking at 127.0.0.1:5601 on the VM that the docker container is running on. I've been trying to play around with VirtualBox NAT and port forwarding from the guest OS to my host OS, but nothing seems to be working., any suggestions?

**Comment by Illuminatian** [comment]
OK, so I'm one step closer! I updated my VirtualBox network adapter to be a bridged adapter, and updated the docker command to bind to the local ip of the VM (192.168.99.101:5601). then, putting that address/port in my host web browser I was able to access the GL dashboard!

Only downside now is i'm pulling no data back from anywhere....so theres that.

**Comment by Illuminatian** [comment]
Holy crap, sorry for the spam Jesus, but I finally got it! I'm going to issue a pull request on the documentation to add the extra configurations that are needed to be done on VirtualBox to enable you to reach the environment from your host internet browser.

**Comment by jgbarah** [comment]
Thank you *very* much!!!! Supporting Windows and VirtualBox is really difficult for us, since we're basically a Linux shop. So, this is really appreciated. Looking forward for your patch to the docs. If you don't have time to write a proper patch, just describe it here and I will try to include the text in the documentation.

**Comment by Illuminatian** [comment]
@jgbarah 

I issued a pull request last week with my additions to the documentation needed to get everything up and running on Windows with Docker Toolbox. As it's my very first pull request/documentation update I've ever done, the formatting on it probably isn't exactly what you're looking for. Please do whatever you need to do to alter it up and make it fit better into your established documentation! I'm just happy I've been able to be of assistance to you guys.

**Comment by jgbarah** [comment]
Where did you upload the pull request? I'm sorry, but I cannot find it... :-(

**Comment by Illuminatian** [comment]
Sorry, a little new to GitHub, it should be out there now.

**Comment by Illuminatian** [comment]
@jgbarah 

Hi! I seem to be getting a new error when using the GrimoireLab/full container. Seems like I'm getting a 401 rate_limit error once again. Any suggestions?

```2018-03-23 22:08:29,425 - grimoire_elk.arthur - ERROR - Error feeding ocean from github (https://github.com/chaoss/wg_diversity_inclusion): 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/arthur.py", line 207, in feed_backend
    ocean_backend.feed()
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/ocean/elastic.py", line 204, in feed
    self.feed_items(items)
  File "/usr/local/lib/python3.5/dist-packages/grimoire_elk/ocean/elastic.py", line 213, in feed_items
    for item in items:
  File "/usr/local/lib/python3.5/dist-packages/perceval/backend.py", line 127, in fetch
    self.client = self._init_client()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 218, in _init_client
    self.archive, from_archive)
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 355, in __init__
    self._init_rate_limit()
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 531, in _init_rate_limit
    raise error
  File "/usr/local/lib/python3.5/dist-packages/perceval/backends/core/github.py", line 525, in _init_rate_limit
    response = super().fetch(url)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 132, in fetch
    response = self._fetch_from_remote(url, payload, headers, method, stream, verify)
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 157, in _fetch_from_remote
    raise e
  File "/usr/local/lib/python3.5/dist-packages/perceval/client.py", line 153, in _fetch_from_remote
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.github.com/rate_limit```

**Comment by Illuminatian** [comment]
Messed with some configurations and determined that somehow my .cfg file got messed up. Issue is resolved.
