### ISSUE TITLE
Proposal to add a Next and Previous Buttons to the Docs

### ISSUE THREAD

**Issue by SteveKola** [chaoss/grimoirelab-tutorial#133]
Every time I'm done reading through a page, I had to scroll up to click on the next page from the sidebar and that's quite a hassle.

I'm thinking maybe it is possible to add the "Previous" and "Next" buttons to the bottom of each page and save the user some stress.

**Comment by vchrombie** [comment]
Hi @SteveKola, thanks for opening the issue.

The tutorial is built using Jekyll and we are currently using a template.

> I'm thinking maybe it is possible to add the "Previous" and "Next" buttons to the bottom of each page and save the user some stress.

The idea is good, but I'm guessing it would be a little hard to implement this because of the sections and sub-sections. All the content is not in a single folder and everything is in markdown. So, in order to make this possible, we have to change the templates and I'm really not sure if it is even possible.

In any case, please let us know if you are interested to give it a try. I can help with reviewing or clarifying any other doubts.

**Comment by SteveKola** [comment]
Hello @vchrombie, 

Thank you for your detailed response. You might have a point about it being difficult to implement since there are sections and sub-sections. 

I'd be happy to give it a try though.

I found the workaround below on StackOverflow. Option 4 stated by the author seems implementable. Do you mind checking it out too and see if it is worth trying out? 
Thanks.

[https://stackoverflow.com/a/40705194/12233153](https://stackoverflow.com/a/40705194/12233153)

**Comment by SteveKola** [comment]
@vchrombie, thank you for the explanation. 

I'm not quite familiar with Jekyll myself, but I think I understand your POV about having to add individual links to each of the md files.

I'd try and see if there's a better way to implement that automatically. 

So should I close the issue or leave it open for now?

**Comment by vchrombie** [comment]
We can close it for now and open it later if that's needed. 
@SteveKola, WDYT?

**Comment by SteveKola** [comment]
Yes, I agree with you. 
I'll close it now.
