### ISSUE TITLE
Update the `gh_edit_branch` configuration

### ISSUE THREAD

**Issue by vchrombie** [chaoss/grimoirelab-tutorial#195]
The `Edit this page on GitHub` link in the footer of every page redirects to the `tesseract` branch of the repository. The `_config.yml` must be updated to point it to the current `master` branch.

**Comment by and3rcg** [comment]
Hello there! I am a beginner in development and open source contributing, so I think I did something wrong according to the [contributors' guide](https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md), since I forked the repo and committed to its master branch. I suppose I can send the fix by creating a new branch in the repo I forked?

**Comment by vchrombie** [comment]
Hi @and3rcg, you are almost there. I see the change in your fork https://github.com/and3rcg/grimoirelab-tutorial/commit/42c10da3752abce0d0805757410b372f995cfc37. You just need to [open the PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Also, the commit message needs to be updated, but I think we can help with that once you open the PR.
https://github.com/chaoss/grimoirelab/blob/master/CONTRIBUTING.md#guidelines-to-follow-to-write-good-commit-messages
