### ISSUE TITLE
Samples cause errors when copy/pasted

### ISSUE THREAD

**Issue by mgalexander** [chaoss/grimoirelab-tutorial#203]
Suggesting that I think there should be a better way to indicate information that will cause a configuration to break when taking samples.

```Error while consuming configuration: Wrong type for section param: githubql studies <class 'str'> should be <class 'list'>```

happens to me every time I copy/paste from the `setup.cfg` examples given on this https://chaoss.github.io/grimoirelab-tutorial/docs/data-sources/configurations/#git (or the others)

I sort of get that I can remove them, but it would be super nice to do something that prevents manual adjustment to go from "do this" to "make this work". Leaving as a topic to discuss though as removal of the suggestion is not good in my mind and a note will go unread/still is the same work to the consumer.

A "copy to deploy" button that does not actually copy those comments and highlight them so it looks intuitive that they are not part of the config, just informative would maybe work.

**Comment by vchrombie** [comment]
Hi @mgalexander, thanks for opening the issue. Sorry for replying late, I missed this issue.

The problem which you have pointed out is really good and it makes very much sense to me because a lot of times many people copy-paste the configurations and forget to delete the `suggested` `optional` words that would attract a lot of errors.

I'm checking if we can use comments in a cfg file so that we can change the configurations accordingly. Even if the users copy-paste it, it shouldn't be a problem. 

Feel free to drop your comments and suggestions.

Also, just to give an update on our current work. We are working on a [new version of Bestiary](https://github.com/chaoss/grimoirelab-bestiary/tree/unicorn) to manage the projects. Will keep the community about its release.

**Comment by vchrombie** [comment]
With merging the PR #215, this issue should be fixed. It would be great if you can give it a try @mgalexander.

Thanks for the opening the issue.
