### ISSUE TITLE
Missing dependency: Cloc

### ISSUE THREAD

**Issue by RCheesley** [chaoss/grimoirelab-tutorial#97]
I'm not sure where to add this in the docs hence raising as an issue for discussion, but in following the tutorials when I got as far as using Graal it became apparent in a rather unspecific error message that I needed to install Cloc - hadn't seen this anywhere as a 'might also need to install' and only came across it when googling for the error message.

My sense would be it needs to feature in basics>supporting?

**Comment by valeriocos** [comment]
Thank you for reporting this issue @RCheesley . You're right the information is available in the Graal repository (https://github.com/chaoss/grimoirelab-graal#how-to-installcreate-the-executables), but not in the tutorial. 

Maybe the external tools used by Graal could be listed at: https://chaoss.github.io/grimoirelab-tutorial/graal/intro.html. Furthermore, the basics section should be also updated, since Graal is not described in https://chaoss.github.io/grimoirelab-tutorial/basics/components.html.

Please @jgbarah share your thoughts ?

**Comment by valeriocos** [comment]
Fixed with https://github.com/chaoss/grimoirelab-tutorial/pull/103

Please @RCheesley check if the fix is OK for you, and feel free to reopen the issue. Thanks!

**Comment by RCheesley** [comment]
Looks good to me!
